name: Update Posts List
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: install
        run: |
          yarn install
      - name: Update Posts List
        run: |
          yarn update-rss
      - name: build & export
        run: |
          yarn build
        env:
          GITHUB_PAGES: true
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: suzuki.dev
